export const FETCH_ALL = "FETCH_ALL";
export const DELETE_POST = "DELETE_POST";
export const ID_TO_UPDATE = "ID_TO_UPDATE";
export const CLEAR_ID_TO_UPDATE = "CLEAR_ID_TO_UPDATE";
export const LOAD_POSTS = "LOAD_POSTS";

export const REQUEST_CREATE_POST = "REQUEST_CREATE_POST";
export const RESPONSE_CREATE_POST = "RESPONSE_CREATE_POST";

export const REQUEST_UPDATE_POST = "REQUEST_UPDATE_POST";
export const RESPONSE_UPDATE_POST = "RESPONSE_UPDATE_POST";

export const LIKE_POST = "LIKE_POST";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
